-- SUPERSEDED — DO NOT APPLY.
--
-- This file created `consume_ai_tokens(p_user_id uuid)`: a SECURITY DEFINER
-- function that took the user id as an argument and carried Postgres's default
-- PUBLIC execute grant. Any caller, signed in or anonymous, could pass any
-- user's id and read that user's subscription status, token limit and remaining
-- quota.
--
-- The replacement takes no arguments and reads `auth.uid()`, so it can only act
-- on the caller. See:
--
--     supabase/migrations/20260816_security_hardening.sql   (section 1)
--
-- Applying the old definition would recreate the vulnerable overload alongside
-- the fixed one, and PostgREST would happily route to it. The body is kept in
-- git history rather than here for that reason.
