-- SUPERSEDED — DO NOT APPLY.
--
-- This file created `record_ai_usage(p_user_id uuid, p_tokens_used bigint)`: a
-- SECURITY DEFINER function that took the target user as an argument, carried
-- Postgres's default PUBLIC execute grant, and did not check the sign of
-- `p_tokens_used`. An anonymous caller could therefore write to any user's
-- quota counter, and a negative value refunded quota rather than consuming it —
-- unlimited free generation for whoever asked.
--
-- The replacement takes only the token count, reads `auth.uid()` for identity,
-- and refuses negative amounts. See:
--
--     supabase/migrations/20260816_security_hardening.sql   (section 1)
--
-- Applying the old definition would recreate the vulnerable overload alongside
-- the fixed one, and PostgREST would happily route to it. The body is kept in
-- git history rather than here for that reason.
